//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintShopProject.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public System.Guid ID { get; set; }
        public System.Guid StatusID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
